# Start with docker-compose up

es1:
  image: elasticsearch
  ports:
  - "9200:9200"
es2:
  image: elasticsearch
es3:
  image: elasticsearch
newrelic:
  image: s12v/newrelic-elasticsearch
  links:
    - es1:elasticsearch
  environment:
    - NEW_RELIC_LICENSE_KEY=itsasecret
